zone: urban
scenarios:
  basic_drive:
    start_link: A219BS010404
    end_link: A219BS010469
    ego_spawn_offset_m: 5.0
    decision_range_m: 40.0
    run_duration_sec: 8.0
    timeout_sec: 0.0
    goal_tolerance_m: 4.0
    check_period_sec: 0.2
    max_laps: 3
    link_speed_ratio: 40
    constant_velocity: 20
  sudden_brake:
    start_link: A219BS010404
    end_link: A219BS010090
    ego_spawn_offset_m: 5.0
    lead_vehicle_offset_m: 25.0
    lead_vehicle_model: 2014_Kia_K7
    lead_vehicle_speed_kph: 25.0
    brake_after_sec: 5.0
    brake_duration_sec: 5.0
    decision_range_m: 30.0
